"""Markdown report -- for PR comments and CI job summaries."""

from __future__ import annotations

from typing import List

from ..audit import Audit
from ..corpus import ATTACKS


def render(audit: Audit) -> str:
    out: List[str] = [f"## rewardlint — `{audit.name}`", ""]

    if audit.passed:
        out += [
            f"✅ No disagreements across **{len(audit.outcomes)}** cases.",
            "",
            f"<sub>call convention: `{audit.call_plan}`</sub>",
            "",
        ]
        return "\n".join(out)

    out += [
        "| | rate | meaning |",
        "|---|---|---|",
        f"| **False positive** | **{audit.false_positive_rate:.0%}** "
        f"| {len(audit.false_positives)} wrong or degenerate completions accepted — the reward-hacking surface |",
        f"| **False negative** | **{audit.false_negative_rate:.0%}** "
        f"| {len(audit.false_negatives)} correct completions rejected — thrown-away learning signal |",
        "",
        f"> **{audit.profile.replace('_', '-')}.** {audit.interpretation}",
        "",
    ]

    if audit.errors:
        out += [
            f"### 💥 {len(audit.errors)} crash(es)",
            "",
            "Your verifier raised on these. Most training loops turn an exception into a "
            "silent zero, which is indistinguishable from a wrong answer.",
            "",
        ]
        out += [f"- `{o.case.id}` — `{o.error}`" for o in audit.errors[:10]]
        out.append("")

    attacks = audit.attacks_that_work
    if attacks:
        out += [f"### 🔴 {len(attacks)} exploit strateg(ies) work", ""]
        for attack, outcomes in sorted(attacks.items()):
            out += [
                f"**`{attack}`** — {ATTACKS.get(attack, '')}",
                "",
                f"{len(outcomes)} case(s) accepted:",
                "",
            ]
            for outcome in outcomes:
                out.append(
                    f"- `{outcome.case.id}` — reference `{_esc(outcome.case.reference)}`, "
                    f"completion `{_esc(_short(outcome.case.completion))}` "
                    f"scored **{outcome.score}**"
                )
            out.append("")

    other = [o for o in audit.false_positives if o.case.category != "exploit"]
    if other:
        out += ["### Wrong answers accepted", "", "| case | reference | completion | why it matters |", "|---|---|---|---|"]
        for outcome in other:
            out.append(
                f"| `{outcome.case.id}` | `{_esc(outcome.case.reference)}` "
                f"| `{_esc(_short(outcome.case.completion))}` | {_esc(outcome.case.why)} |"
            )
        out.append("")

    if audit.false_negatives:
        out += [
            "<details><summary>"
            f"{len(audit.false_negatives)} correct answers rejected</summary>",
            "",
            "| case | reference | completion | why it should pass |",
            "|---|---|---|---|",
        ]
        for outcome in audit.false_negatives:
            out.append(
                f"| `{outcome.case.id}` | `{_esc(outcome.case.reference)}` "
                f"| `{_esc(_short(outcome.case.completion))}` | {_esc(outcome.case.why)} |"
            )
        out += ["", "</details>", ""]

    out += [
        f"<sub>call convention: `{audit.call_plan}` · "
        f"corpus: {len(audit.outcomes)} cases · "
        "generated by [rewardlint](https://github.com/junglezke/rewardlint)</sub>",
    ]
    return "\n".join(out)


def _short(text: str, limit: int = 70) -> str:
    shown = text.replace("\n", "\\n")
    return shown if len(shown) <= limit else shown[: limit - 3] + "..."


def _esc(text: str) -> str:
    return text.replace("|", "\\|").replace("`", "'")
